const PROJECTS = [
  {
    id: "iga-lancome",
    label: "Iga Świątek x Lancome",
    type: "folder",
    iconType: "folder",
    position: { top: "8%", left: "12%" },
    contentStatus: "ready",
    title: "IGA ŚWIĄTEK X LANCOME",
    subtitle: "campaign creative",
    client: "Lancome",
    year: "2024",
    textFile: "assets/projects/iga-lancome/IGA ŚWIĄTEK X LANCÔME.txt",
    body: [],
    images: [
      "assets/projects/iga-lancome/iga-lancome-2.jpg",
      "assets/projects/iga-lancome/442155504_1841095423021200_7605963034017097109_n.webp",
      "assets/projects/iga-lancome/485186989_1055871003246047_1550396077494746513_n.jpg",
      "assets/projects/iga-lancome/img6f0LyH-a2256e2.jpg",
      "assets/projects/iga-lancome/vrewzhxf1rfj6zu9yxry.jpg",
    ],
    videos: [
      "assets/projects/iga-lancome/LANCOME x Iga Świątek 8 (1).mp4",
    ],
    thumbnail: "assets/projects/iga-lancome/iga-lancome-2.jpg",
  },
  {
    id: "tenders",
    label: "TENDERS",
    type: "folder",
    iconType: "folder",
    position: { top: "32%", left: "10%" },
    contentStatus: "placeholder",
    title: "TENDERS",
    subtitle: "pitches & proposals",
    client: "Various",
    body: [
      "Selected tender pitches and proposals. Replace with your copy and campaign visuals.",
    ],
    images: [],
    thumbnail: null,
  },
  {
    id: "mcdonalds",
    label: "McDonald's",
    type: "folder",
    iconType: "folder",
    position: { top: "58%", left: "14%" },
    contentStatus: "placeholder",
    title: "MCDONALD'S",
    subtitle: "campaign creative",
    client: "McDonald's",
    body: [
      "McDonald's campaign folder. Drop images into assets/projects/mcdonalds/ and list them in order in images[].",
    ],
    images: [],
    thumbnail: null,
  },
  {
    id: "lavazza-wosp",
    label: "Lavazza x WOŚP",
    type: "folder",
    iconType: "folder",
    position: { top: "38%", left: "72%" },
    contentStatus: "ready",
    title: "LAVAZZA X WOŚP",
    subtitle: "campaign creative",
    client: "Lavazza x WOŚP",
    textFile: "assets/projects/lavazza-wosp/lavazzaa.txt",
    body: [],
    images: [
      "assets/projects/lavazza-wosp/PREVIEW_master_layout_WOSPxLAVAZZA_B3_2023_V7.jpg",
    ],
    videos: [
      "assets/projects/lavazza-wosp/Lavazza x WOŚP - relacja z wydarzenia wersja 2 21.02.24'.mp4",
    ],
    thumbnail: "assets/projects/lavazza-wosp/PREVIEW_master_layout_WOSPxLAVAZZA_B3_2023_V7.jpg",
  },
  {
    id: "loreal-pdf",
    label: "L'Oreal.pdf",
    type: "pdf",
    iconType: "pdf",
    position: { top: "72%", left: "10%" },
    contentStatus: "placeholder",
    client: "L'Oreal",
    role: "Creative",
    year: "",
    description:
      "Campaign deck and presentation materials for L'Oreal.",
    pdf: "assets/projects/loreal/deck.pdf",
    thumbnail: null,
  },
  {
    id: "pezet-mp3",
    label: "PEZET X POPKILLERY.mp3",
    type: "audio",
    iconType: "audio",
    position: { top: "78%", left: "68%" },
    contentStatus: "placeholder",
    client: "Pezet x Popkillery",
    role: "Creative",
    year: "",
    description:
      "Audio piece for Pezet x Popkillery collaboration.",
    audio: "assets/projects/pezet/track.mp3",
    thumbnail: null,
  },
  {
    id: "kizo",
    label: "KIZO.webp",
    type: "image",
    iconType: "image",
    position: { top: "10%", left: "78%" },
    contentStatus: "placeholder",
    client: "Kizo",
    role: "Creative",
    year: "",
    description: "Kizo campaign visual. Add hero image to assets/projects/kizo/hero.webp.",
    hero: "assets/projects/kizo/hero.webp",
    thumbnail: "assets/projects/kizo/hero.webp",
  },
  {
    id: "lipton-snowfest",
    label: "Lipton x SNOWFEST.jpg",
    type: "image",
    iconType: "image",
    contentLayout: "case-study",
    position: { top: "68%", left: "82%" },
    contentStatus: "ready",
    title: "LIPTON X SNOWFEST",
    subtitle: "event production & creative",
    client: "Lipton",
    textFile: "assets/projects/lipton-snowfest/lipton.txt",
    body: [],
    images: [
      "assets/projects/lipton-snowfest/1.png",
      "assets/projects/lipton-snowfest/2.png",
      "assets/projects/lipton-snowfest/3.png",
      "assets/projects/lipton-snowfest/snowfest1.2.1-60e02f8.jpg",
      "assets/projects/lipton-snowfest/snowfest1.22.1-9b66f6f.jpg",
      "assets/projects/lipton-snowfest/snowfest1.26.1-2e3aa1e.webp",
      "assets/projects/lipton-snowfest/snowfest1.32.1-b0cffcd.webp",
    ],
    thumbnail: "assets/projects/lipton-snowfest/1.png",
    thumbnailTall: true,
  },
];
