const PROJECTS = [
  {
    id: "iga-lancome",
    label: "Iga Świątek x Lancome",
    type: "folder",
    iconType: "folder",
    position: { top: "10%", left: "10%" },
    contentStatus: "ready",
    title: "IGA ŚWIĄTEK X LANCOME",
    subtitle: "campaign creative",
    client: "Lancome",
    year: "2024",
    textFile: "assets/projects/iga-lancome/IGA ŚWIĄTEK X LANCÔME.txt",
    body: [],
    images: [
      "assets/projects/iga-lancome/iga-lancome-2.jpg",
      "assets/projects/iga-lancome/442155504_1841095423021200_7605963034017097109_n.webp",
      "assets/projects/iga-lancome/485186989_1055871003246047_1550396077494746513_n.jpg",
      "assets/projects/iga-lancome/img6f0LyH-a2256e2.jpg",
      "assets/projects/iga-lancome/vrewzhxf1rfj6zu9yxry.jpg",
    ],
    videos: [
      "assets/projects/iga-lancome/LANCOME x Iga Świątek 8 (1).mp4",
    ],
    thumbnail: "assets/projects/iga-lancome/iga-lancome-2.jpg",
  },
  {
    id: "tenders",
    label: "TENDERS",
    type: "folder",
    iconType: "folder",
    position: { top: "10%", left: "28%" },
    contentStatus: "ready",
    title: "TENDERS",
    subtitle: "pitches & proposals",
    client: "Various",
    textFile: "assets/projects/tenders/tenders.txt",
    body: [],
    images: [
      "assets/projects/tenders/Garnier-logo.jpg",
      "assets/projects/tenders/L'Oréal_logo.svg.png",
      "assets/projects/tenders/LIPTON_Teas_and_Infusions_Logo.jpg",
      "assets/projects/tenders/Maybelline-Logo.svg.png",
      "assets/projects/tenders/NYX-logo.png",
    ],
    thumbnail: "assets/projects/tenders/L'Oréal_logo.svg.png",
  },
  {
    id: "campari",
    label: "Campari",
    type: "folder",
    iconType: "folder",
    position: { top: "10%", left: "46%" },
    contentStatus: "ready",
    title: "CAMPARI",
    subtitle: "campaign creative",
    client: "Campari",
    textFile: "assets/projects/campari/campari.docx",
    body: [],
    images: [
      "assets/projects/campari/Zrzut ekranu 2026-05-21 o 22.44.46.png",
    ],
    thumbnail: "assets/projects/campari/Zrzut ekranu 2026-05-21 o 22.44.46.png",
  },
  {
    id: "hbo-alice",
    label: "HBO x Bring Back Alice",
    type: "folder",
    iconType: "folder",
    position: { top: "10%", left: "64%" },
    contentStatus: "ready",
    title: "HBO X BRING BACK ALICE",
    subtitle: "production",
    client: "HBO",
    textFile: "assets/projects/HBO/HBO x Bring Back Alice.txt",
    body: [],
    images: [
      "assets/projects/HBO/65093.6.jpg",
      "assets/projects/HBO/fsusizjxsaa2e7f.jpg",
    ],
    videos: ["assets/projects/HBO/bring back alice.mp4"],
    thumbnail: "assets/projects/HBO/65093.6.jpg",
  },
  {
    id: "kizo",
    label: "KIZO",
    type: "folder",
    iconType: "folder",
    position: { top: "10%", left: "82%" },
    contentStatus: "ready",
    title: "KIZO",
    subtitle: "ongoing creative production",
    client: "Kizo",
    textFile: "assets/projects/kizo/Kizo.txt",
    body: [],
    images: [
      "assets/projects/kizo/kizo-2-1000x600.jpg",
      "assets/projects/kizo/kizo-3.jpg",
      "assets/projects/kizo/hq720.jpg",
      "assets/projects/kizo/maxresdefault (1).jpg",
      "assets/projects/kizo/maxresdefault-kopia.jpg",
    ],
    thumbnail: "assets/projects/kizo/kizo-2-1000x600.jpg",
  },
  {
    id: "lavazza-wosp",
    label: "Lavazza x WOŚP",
    type: "folder",
    iconType: "folder",
    position: { top: "72%", left: "12%" },
    contentStatus: "ready",
    title: "LAVAZZA X WOŚP",
    subtitle: "campaign creative",
    client: "Lavazza x WOŚP",
    textFile: "assets/projects/lavazza-wosp/lavazzaa.txt",
    body: [],
    images: [
      "assets/projects/lavazza-wosp/PREVIEW_master_layout_WOSPxLAVAZZA_B3_2023_V7.jpg",
    ],
    videos: [
      "assets/projects/lavazza-wosp/Lavazza x WOŚP - relacja z wydarzenia wersja 2 21.02.24'.mp4",
    ],
    thumbnail: "assets/projects/lavazza-wosp/PREVIEW_master_layout_WOSPxLAVAZZA_B3_2023_V7.jpg",
  },
  {
    id: "lipton-snowfest",
    label: "Lipton x SNOWFEST",
    type: "folder",
    iconType: "folder",
    position: { top: "72%", left: "50%" },
    contentStatus: "ready",
    title: "LIPTON X SNOWFEST",
    subtitle: "event production & creative",
    client: "Lipton",
    textFile: "assets/projects/lipton-snowfest/lipton.txt",
    body: [],
    images: [
      "assets/projects/lipton-snowfest/1.png",
      "assets/projects/lipton-snowfest/2.png",
      "assets/projects/lipton-snowfest/3.png",
      "assets/projects/lipton-snowfest/snowfest1.2.1-60e02f8.jpg",
      "assets/projects/lipton-snowfest/snowfest1.22.1-9b66f6f.jpg",
      "assets/projects/lipton-snowfest/snowfest1.26.1-2e3aa1e.webp",
      "assets/projects/lipton-snowfest/snowfest1.32.1-b0cffcd.webp",
    ],
    thumbnail: "assets/projects/lipton-snowfest/1.png",
  },
];
